# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Backend-install:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: use Node.js
      working-directory: Backend
      run: yarn --ignore-engines --frozen-lockfile
    - run: yarn --ignore-engines --frozen-lockfile 


  Backend-build:

    runs-on: ubuntu-latest
    needs: Backend-install 

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: use Node.js
      working-directory: Backend
      run: yarn --ignore-engines --frozen-lockfile
    - name: build backend
      working-directory: Backend
      run: yarn build

  Frontend-install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: use Node.js
      working-directory: Frontend
      run: yarn --ignore-engines --frozen-lockfile
    - run: yarn --ignore-engines --frozen-lockfile 


  Frontend-build:

    runs-on: ubuntu-latest
    needs: Frontend-install 

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: use Node.js
      working-directory: Frontend
      run: yarn --ignore-engines --frozen-lockfile
    - name: build frontend
      working-directory: Frontend
      run: yarn build
